[
  ./core.nix
  ./config/conditions.nix
  ./config/erlang-inet
  ./config/vhosts.nix
  ./config/imperative-containers.nix
  ./services/dyndns
  ./services/epmd
  ./services/lighttpd.nix
  ./services/mongooseim
  ./services/mongooseim/ctl.nix
  ./services/nix-ssh-build.nix
  ./services/nsd-zone-writer
  ./services/postfix
  ./services/webspace
]
